using System.Collections.Generic;
using AllEnum;

namespace PokemonGo.RocketAPI.Console
{
    class ReferenceData
    {
        public struct PokeEvolutionData
        {
            public PokemonFamilyId PokemonFamily;
            public int CandyToEvolve;
            public int EvolutionLevel;
            public double CPMultiplier;

            public PokeEvolutionData(PokemonFamilyId pokemonFamily, int candyToEvolve, int evolutionLevel, double cpMultiplier)
            {
                PokemonFamily = pokemonFamily;
                CandyToEvolve = candyToEvolve;
                EvolutionLevel = evolutionLevel;
                CPMultiplier = cpMultiplier;
            }
        }

        public static Dictionary<PokemonId, PokeEvolutionData> EvolutionData = new Dictionary<PokemonId, PokeEvolutionData>()
        {
            {PokemonId.Bulbasaur, new PokeEvolutionData(PokemonFamilyId.FamilyBulbasaur, 25, 1, 13.7) },
            {PokemonId.Ivysaur, new PokeEvolutionData(PokemonFamilyId.FamilyBulbasaur, 100, 2, 21.4) },
            {PokemonId.Venusaur, new PokeEvolutionData(PokemonFamilyId.FamilyBulbasaur, 0, 3, 34.6) },
            {PokemonId.Charmander, new PokeEvolutionData(PokemonFamilyId.FamilyCharmander, 25, 1, 12.2) },
            {PokemonId.Charmeleon, new PokeEvolutionData(PokemonFamilyId.FamilyCharmander, 100, 2, 20.4) },
            {PokemonId.Charizard, new PokeEvolutionData(PokemonFamilyId.FamilyCharmander, 0, 3, 34.9) },
            {PokemonId.Squirtle, new PokeEvolutionData(PokemonFamilyId.FamilySquirtle, 25, 1, 12.9) },
            {PokemonId.Wartortle, new PokeEvolutionData(PokemonFamilyId.FamilySquirtle, 100, 2, 20.7) },
            {PokemonId.Blastoise, new PokeEvolutionData(PokemonFamilyId.FamilySquirtle, 0, 3, 34) },
            {PokemonId.Caterpie, new PokeEvolutionData(PokemonFamilyId.FamilyCaterpie, 12, 1, 5.3) },
            {PokemonId.Metapod, new PokeEvolutionData(PokemonFamilyId.FamilyCaterpie, 50, 2, 5.7) },
            {PokemonId.Butterfree, new PokeEvolutionData(PokemonFamilyId.FamilyCaterpie, 0, 3, 19) },
            {PokemonId.Weedle, new PokeEvolutionData(PokemonFamilyId.FamilyWeedle, 12, 1, 5.4) },
            {PokemonId.Kakuna, new PokeEvolutionData(PokemonFamilyId.FamilyWeedle, 50, 2, 5.9) },
            {PokemonId.Beedrill, new PokeEvolutionData(PokemonFamilyId.FamilyWeedle, 0, 3, 18.8) },
            {PokemonId.Pidgey, new PokeEvolutionData(PokemonFamilyId.FamilyPidgey, 12, 1, 8.5) },
            {PokemonId.Pidgeotto, new PokeEvolutionData(PokemonFamilyId.FamilyPidgey, 50, 2, 15.8) },
            {PokemonId.Pidgeot, new PokeEvolutionData(PokemonFamilyId.FamilyPidgey, 0, 3, 27.8) },
            {PokemonId.Rattata, new PokeEvolutionData(PokemonFamilyId.FamilyRattata, 25, 1, 7.1) },
            {PokemonId.Raticate, new PokeEvolutionData(PokemonFamilyId.FamilyRattata, 0, 2, 18.8) },
            {PokemonId.Spearow, new PokeEvolutionData(PokemonFamilyId.FamilySpearow, 50, 1, 8.5) },
            {PokemonId.Fearow, new PokeEvolutionData(PokemonFamilyId.FamilySpearow, 0, 2, 23) },
            {PokemonId.Ekans, new PokeEvolutionData(PokemonFamilyId.FamilyEkans, 50, 1, 10.4) },
            {PokemonId.Arbok, new PokeEvolutionData(PokemonFamilyId.FamilyEkans, 0, 2, 23.3) },
            {PokemonId.Pikachu, new PokeEvolutionData(PokemonFamilyId.FamilyPikachu, 50, 1, 11.2) },
            {PokemonId.Raichu, new PokeEvolutionData(PokemonFamilyId.FamilyPikachu, 0, 2, 26.9) },
            {PokemonId.Sandshrew, new PokeEvolutionData(PokemonFamilyId.FamilySandshrew, 50, 1, 10.1) },
            {PokemonId.Sandlash, new PokeEvolutionData(PokemonFamilyId.FamilySandshrew, 0, 2, 23.9) },
            {PokemonId.NidoranFemale, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran, 25, 1, 11.1) },
            {PokemonId.Nidorina, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran, 100, 2, 18.3) },
            {PokemonId.Nidoqueen, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran, 0, 3, 33.3) },
            {PokemonId.NidoranMale, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran2, 25, 1, 10.7) },
            {PokemonId.Nidorino, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran2, 100, 2, 17.9) },
            {PokemonId.Nidoking, new PokeEvolutionData(PokemonFamilyId.FamilyNidoran2, 0, 3, 33.1) },
            {PokemonId.Clefairy, new PokeEvolutionData(PokemonFamilyId.FamilyClefairy, 50, 1, 15.5) },
            {PokemonId.Clefable, new PokeEvolutionData(PokemonFamilyId.FamilyClefairy, 0, 2, 32) },
            {PokemonId.Vulpix, new PokeEvolutionData(PokemonFamilyId.FamilyVulpix, 50, 1, 10.5) },
            {PokemonId.Ninetales, new PokeEvolutionData(PokemonFamilyId.FamilyVulpix, 0, 2, 29.1) },
            {PokemonId.Jigglypuff, new PokeEvolutionData(PokemonFamilyId.FamilyJigglypuff, 50, 1, 11.5) },
            {PokemonId.Wigglytuff, new PokeEvolutionData(PokemonFamilyId.FamilyJigglypuff, 0, 2, 28.9) },
            {PokemonId.Zubat, new PokeEvolutionData(PokemonFamilyId.FamilyZubat, 50, 1, 8) },
            {PokemonId.Golbat, new PokeEvolutionData(PokemonFamilyId.FamilyZubat, 0, 2, 25.4) },
            {PokemonId.Oddish, new PokeEvolutionData(PokemonFamilyId.FamilyOddish, 25, 1, 14.8) },
            {PokemonId.Gloom, new PokeEvolutionData(PokemonFamilyId.FamilyOddish, 100, 2, 22.2) },
            {PokemonId.Vileplume, new PokeEvolutionData(PokemonFamilyId.FamilyOddish, 0, 3, 33.3) },
            {PokemonId.Paras, new PokeEvolutionData(PokemonFamilyId.FamilyParas, 50, 1, 11.6) },
            {PokemonId.Parasect, new PokeEvolutionData(PokemonFamilyId.FamilyParas, 0, 2, 23) },
            {PokemonId.Venonat, new PokeEvolutionData(PokemonFamilyId.FamilyVenonat, 50, 1, 13.2) },
            {PokemonId.Venomoth, new PokeEvolutionData(PokemonFamilyId.FamilyVenonat, 0, 2, 25) },
            {PokemonId.Diglett, new PokeEvolutionData(PokemonFamilyId.FamilyDiglett, 50, 1, 5.3) },
            {PokemonId.Dugtrio, new PokeEvolutionData(PokemonFamilyId.FamilyDiglett, 0, 2, 15) },
            {PokemonId.Meowth, new PokeEvolutionData(PokemonFamilyId.FamilyMeowth, 50, 1, 9.5) },
            {PokemonId.Persian, new PokeEvolutionData(PokemonFamilyId.FamilyMeowth, 0, 2, 21.4) },
            {PokemonId.Psyduck, new PokeEvolutionData(PokemonFamilyId.FamilyPsyduck, 50, 1, 14.3) },
            {PokemonId.Golduck, new PokeEvolutionData(PokemonFamilyId.FamilyPsyduck, 0, 2, 31.9) },
            {PokemonId.Mankey, new PokeEvolutionData(PokemonFamilyId.FamilyMankey, 50, 1, 11.1) },
            {PokemonId.Primeape, new PokeEvolutionData(PokemonFamilyId.FamilyMankey, 0, 2, 24.6) },
            {PokemonId.Growlithe, new PokeEvolutionData(PokemonFamilyId.FamilyGrowlithe, 50, 1, 17.3) },
            {PokemonId.Arcanine, new PokeEvolutionData(PokemonFamilyId.FamilyGrowlithe, 0, 2, 40.2) },
            {PokemonId.Poliwag, new PokeEvolutionData(PokemonFamilyId.FamilyPoliwag, 25, 1, 10) },
            {PokemonId.Poliwhirl, new PokeEvolutionData(PokemonFamilyId.FamilyPoliwag, 100, 2, 17.4) },
            {PokemonId.Poliwrath, new PokeEvolutionData(PokemonFamilyId.FamilyPoliwag, 0, 3, 33.5) },
            {PokemonId.Abra, new PokeEvolutionData(PokemonFamilyId.FamilyAbra, 25, 1, 7.3) },
            {PokemonId.Kadabra, new PokeEvolutionData(PokemonFamilyId.FamilyAbra, 100, 2, 14.5) },
            {PokemonId.Alakhazam, new PokeEvolutionData(PokemonFamilyId.FamilyAbra, 0, 3, 23.9) },
            {PokemonId.Machop, new PokeEvolutionData(PokemonFamilyId.FamilyMachop, 25, 1, 14) },
            {PokemonId.Machoke, new PokeEvolutionData(PokemonFamilyId.FamilyMachop, 100, 2, 23.2) },
            {PokemonId.Machamp, new PokeEvolutionData(PokemonFamilyId.FamilyMachop, 0, 3, 34.8) },
            {PokemonId.Bellsprout, new PokeEvolutionData(PokemonFamilyId.FamilyBellsprout, 25, 1, 14.3) },
            {PokemonId.Weepinbell, new PokeEvolutionData(PokemonFamilyId.FamilyBellsprout, 100, 2, 22.7) },
            {PokemonId.Victreebell, new PokeEvolutionData(PokemonFamilyId.FamilyBellsprout, 0, 3, 33.9) },
            {PokemonId.Tentacool, new PokeEvolutionData(PokemonFamilyId.FamilyTentacool, 50, 1, 11.5) },
            {PokemonId.Tentacruel, new PokeEvolutionData(PokemonFamilyId.FamilyTentacool, 0, 2, 29.6) },
            {PokemonId.Geodude, new PokeEvolutionData(PokemonFamilyId.FamilyGeodude, 25, 1, 10.7) },
            {PokemonId.Graveler, new PokeEvolutionData(PokemonFamilyId.FamilyGeodude, 100, 2, 18.7) },
            {PokemonId.Golem, new PokeEvolutionData(PokemonFamilyId.FamilyGeodude, 0, 3, 30.7) },
            {PokemonId.Ponyta, new PokeEvolutionData(PokemonFamilyId.FamilyPonyta, 50, 1, 19.8) },
            {PokemonId.Rapidash, new PokeEvolutionData(PokemonFamilyId.FamilyPonyta, 0, 2, 29.3) },
            {PokemonId.Slowpoke, new PokeEvolutionData(PokemonFamilyId.FamilySlowpoke, 50, 1, 15.7) },
            {PokemonId.Slowbro, new PokeEvolutionData(PokemonFamilyId.FamilySlowpoke, 0, 2, 34.8) },
            {PokemonId.Magnemite, new PokeEvolutionData(PokemonFamilyId.FamilyMagnemite, 50, 1, 11.2) },
            {PokemonId.Magneton, new PokeEvolutionData(PokemonFamilyId.FamilyMagnemite, 0, 2, 24.8) },
            {PokemonId.Farfetchd, new PokeEvolutionData(PokemonFamilyId.FamilyFarfetchd, 0, 1, 16.4) },
            {PokemonId.Doduo, new PokeEvolutionData(PokemonFamilyId.FamilyDoduo, 50, 1, 10.8) },
            {PokemonId.Dodrio, new PokeEvolutionData(PokemonFamilyId.FamilyDoduo, 0, 2, 24.2) },
            {PokemonId.Seel, new PokeEvolutionData(PokemonFamilyId.FamilySeel, 50, 1, 14.2) },
            {PokemonId.Dewgong, new PokeEvolutionData(PokemonFamilyId.FamilySeel, 0, 2, 28.5) },
            {PokemonId.Grimer, new PokeEvolutionData(PokemonFamilyId.FamilyGrimer, 50, 1, 16.6) },
            {PokemonId.Muk, new PokeEvolutionData(PokemonFamilyId.FamilyGrimer, 0, 2, 34.9) },
            {PokemonId.Shellder, new PokeEvolutionData(PokemonFamilyId.FamilyShellder, 50, 1, 10.3) },
            {PokemonId.Cloyster, new PokeEvolutionData(PokemonFamilyId.FamilyShellder, 0, 2, 27.2) },
            {PokemonId.Gastly, new PokeEvolutionData(PokemonFamilyId.FamilyGastly, 25, 1, 10.1) },
            {PokemonId.Haunter, new PokeEvolutionData(PokemonFamilyId.FamilyGastly, 100, 2, 17.9) },
            {PokemonId.Gengar, new PokeEvolutionData(PokemonFamilyId.FamilyGastly, 0, 3, 27.6) },
            {PokemonId.Onix, new PokeEvolutionData(PokemonFamilyId.FamilyOnix, 0, 1, 10.8) },
            {PokemonId.Drowzee, new PokeEvolutionData(PokemonFamilyId.FamilyDrowzee, 50, 1, 13.8) },
            {PokemonId.Hypno, new PokeEvolutionData(PokemonFamilyId.FamilyDrowzee, 0, 2, 29.1) },
            {PokemonId.Krabby, new PokeEvolutionData(PokemonFamilyId.FamilyKrabby, 50, 1, 9.9) },
            {PokemonId.Kingler, new PokeEvolutionData(PokemonFamilyId.FamilyKrabby, 0, 2, 24) },
            {PokemonId.Voltorb, new PokeEvolutionData(PokemonFamilyId.FamilyVoltorb, 50, 1, 10.6) },
            {PokemonId.Electrode, new PokeEvolutionData(PokemonFamilyId.FamilyVoltorb, 0, 2, 21.6) },
            {PokemonId.Exeggcute, new PokeEvolutionData(PokemonFamilyId.FamilyExeggcute, 50, 1, 14.1) },
            {PokemonId.Exeggutor, new PokeEvolutionData(PokemonFamilyId.FamilyExeggcute, 0, 2, 39.8) },
            {PokemonId.Cubone, new PokeEvolutionData(PokemonFamilyId.FamilyCubone, 50, 1, 12.9) },
            {PokemonId.Marowak, new PokeEvolutionData(PokemonFamilyId.FamilyCubone, 0, 2, 21.8) },
            {PokemonId.Hitmonlee, new PokeEvolutionData(PokemonFamilyId.FamilyHitmonlee, 0, 1, 19.5) },
            {PokemonId.Hitmonchan, new PokeEvolutionData(PokemonFamilyId.FamilyHitmonchan, 0, 1, 19.8) },
            {PokemonId.Lickitung, new PokeEvolutionData(PokemonFamilyId.FamilyLickitung, 0, 1, 21.4) },
            {PokemonId.Koffing, new PokeEvolutionData(PokemonFamilyId.FamilyKoffing, 50, 1, 14.8) },
            {PokemonId.Weezing, new PokeEvolutionData(PokemonFamilyId.FamilyKoffing, 0, 2, 30) },
            {PokemonId.Rhyhorn, new PokeEvolutionData(PokemonFamilyId.FamilyRhyhorn, 50, 1, 15.3) },
            {PokemonId.Rhydon, new PokeEvolutionData(PokemonFamilyId.FamilyRhyhorn, 0, 2, 29.9) },
            {PokemonId.Chansey, new PokeEvolutionData(PokemonFamilyId.FamilyChansey, 0, 1, 7.9) },
            {PokemonId.Tangela, new PokeEvolutionData(PokemonFamilyId.FamilyTangela, 0, 1, 22.9) },
            {PokemonId.Kangaskhan, new PokeEvolutionData(PokemonFamilyId.FamilyKangaskhan, 0, 1, 27.1) },
            {PokemonId.Horsea, new PokeEvolutionData(PokemonFamilyId.FamilyHorsea, 50, 1, 10) },
            {PokemonId.Seadra, new PokeEvolutionData(PokemonFamilyId.FamilyHorsea, 0, 2, 22.5) },
            {PokemonId.Goldeen, new PokeEvolutionData(PokemonFamilyId.FamilyGoldeen, 50, 1, 12.3) },
            {PokemonId.Seaking, new PokeEvolutionData(PokemonFamilyId.FamilyGoldeen, 0, 2, 27.1) },
            {PokemonId.Staryu, new PokeEvolutionData(PokemonFamilyId.FamilyStaryu, 50, 1, 11.9) },
            {PokemonId.Starmie, new PokeEvolutionData(PokemonFamilyId.FamilyStaryu, 0, 2, 29) },
            {PokemonId.MrMime, new PokeEvolutionData(PokemonFamilyId.FamilyMrMime, 0, 1, 19.4) },
            {PokemonId.Scyther, new PokeEvolutionData(PokemonFamilyId.FamilyScyther, 0, 1, 27.5) },
            {PokemonId.Jynx, new PokeEvolutionData(PokemonFamilyId.FamilyJynx, 0, 1, 22.6) },
            {PokemonId.Electabuzz, new PokeEvolutionData(PokemonFamilyId.FamilyElectabuzz, 0, 1, 28.1) },
            {PokemonId.Magmar, new PokeEvolutionData(PokemonFamilyId.FamilyMagmar, 0, 1, 30.2) },
            {PokemonId.Pinsir, new PokeEvolutionData(PokemonFamilyId.FamilyPinsir, 0, 1, 28.2) },
            {PokemonId.Tauros, new PokeEvolutionData(PokemonFamilyId.FamilyTauros, 0, 1, 24.4) },
            {PokemonId.Magikarp, new PokeEvolutionData(PokemonFamilyId.FamilyMagikarp, 400, 1, 2.9) },
            {PokemonId.Gyarados, new PokeEvolutionData(PokemonFamilyId.FamilyMagikarp, 0, 2, 36.1) },
            {PokemonId.Lapras, new PokeEvolutionData(PokemonFamilyId.FamilyLapras, 0, 1, 40.1) },
            {PokemonId.Ditto, new PokeEvolutionData(PokemonFamilyId.FamilyDitto, 0, 1, 40) },
            {PokemonId.Eevee, new PokeEvolutionData(PokemonFamilyId.FamilyEevee, 25, 1, 13.8) },
            {PokemonId.Vaporeon, new PokeEvolutionData(PokemonFamilyId.FamilyEevee, 0, 2, 37.8) },
            {PokemonId.Jolteon, new PokeEvolutionData(PokemonFamilyId.FamilyEevee, 0, 3, 28.4) },
            {PokemonId.Flareon, new PokeEvolutionData(PokemonFamilyId.FamilyEevee, 0, 4, 35.4) },
            {PokemonId.Porygon, new PokeEvolutionData(PokemonFamilyId.FamilyPorygon, 0, 1, 22.3) },
            {PokemonId.Omanyte, new PokeEvolutionData(PokemonFamilyId.FamilyOmanyte, 50, 1, 14.3) },
            {PokemonId.Omastar, new PokeEvolutionData(PokemonFamilyId.FamilyOmanyte, 0, 2, 29.7) },
            {PokemonId.Kabuto, new PokeEvolutionData(PokemonFamilyId.FamilyKabuto, 50, 1, 14.1) },
            {PokemonId.Kabutops, new PokeEvolutionData(PokemonFamilyId.FamilyKabuto, 0, 2, 28.3) },
            {PokemonId.Aerodactyl, new PokeEvolutionData(PokemonFamilyId.FamilyAerodactyl, 0, 1, 28.8) },
            {PokemonId.Snorlax, new PokeEvolutionData(PokemonFamilyId.FamilySnorlax, 0, 1, 41.9) },
            {PokemonId.Articuno, new PokeEvolutionData(PokemonFamilyId.FamilyArticuno, 0, 1, 50) },
            {PokemonId.Zapdos, new PokeEvolutionData(PokemonFamilyId.FamilyZapdos, 0, 1, 50) },
            {PokemonId.Moltres, new PokeEvolutionData(PokemonFamilyId.FamilyMoltres, 0, 1, 50) },
            {PokemonId.Dratini, new PokeEvolutionData(PokemonFamilyId.FamilyDratini, 25, 1, 12.5) },
            {PokemonId.Dragonair, new PokeEvolutionData(PokemonFamilyId.FamilyDratini, 100, 2, 23) },
            {PokemonId.Dragonite, new PokeEvolutionData(PokemonFamilyId.FamilyDratini, 0, 3, 47.4) },
            {PokemonId.Mewtwo, new PokeEvolutionData(PokemonFamilyId.FamilyMewtwo, 0, 1, 50) },
            {PokemonId.Mew, new PokeEvolutionData(PokemonFamilyId.FamilyMew, 0, 1, 50) },
        };
    }
}
